### ISSUE TITLE
Uncaught TypeError after 0.6.0 Upgrade

### ISSUE THREAD

**Issue by alvincrespo** [simplabs/ember-simple-auth#217]
I'm getting a `Uncaught TypeError: undefined is not a function` error after upgrading to 0.6.0

**Stack Trace**

```
__exports__.default.Ember.ObjectProxy.extend.bindToStoreEvents (vendor.js:161058)
__exports__.default.Ember.ObjectProxy.extend.init (vendor.js:160902)
apply (vendor.js:31275)
superWrapper (vendor.js:30855)
apply (vendor.js:31275)
Class (vendor.js:45389)
Mixin.create.create (vendor.js:45827)
__exports__.default (vendor.js:161126)
__exports__.default.initialize (vendor.js:160376)
(anonymous function) (vendor.js:15872)
visit (vendor.js:16271)
visit (vendor.js:16269)
DAG.topsort (vendor.js:16325)
Namespace.extend.runInitializers (vendor.js:15869)
Namespace.extend._initialize (vendor.js:15754)
Backburner.run (vendor.js:13349)
apply (vendor.js:31278)
run (vendor.js:29905)
runInitialize (vendor.js:15553)
jQuery.Callbacks.fire (vendor.js:3214)
jQuery.Callbacks.self.fireWith (vendor.js:3326)
jQuery.extend.ready (vendor.js:3538)
completed (vendor.js:3569)
Node.addEventListener("DOMContentLoaded") (async)
jQuery.ready.promise (vendor.js:3588)
jQuery.fn.ready (vendor.js:3494)
jQuery.fn.init (vendor.js:2934)
jQuery (vendor.js:168)
(anonymous function) (vendor.js:3652)
deletedIds (vendor.js:129)
(anonymous function) (vendor.js:133)
```

**Specs**

```
➜  ~  npm -v
1.4.13
➜  ~  node -v
v0.10.28
➜  ~  ember -v
version: 0.0.36
```

**Brocfile**

```
app.import('vendor/ember-simple-auth/simple-auth.js');
app.import('vendor/ember-simple-auth/simple-auth-oauth2.js');
```

**Initializer**

```
# Simple Auth Configuration
window.ENV = window.ENV || {}
window.ENV['simple-auth'] = {
  storeFactory: "simple-auth-authorizer:oauth2-bearer"
  crossOriginWhitelist: [ENV.HOST]
}

CustomAuthenticator = SimpleAuth.Authenticators.OAuth2.extend
  serverTokenEndpoint: ENV.HOST + "/token"
  authenticate: (credentials) ->
    new Em.RSVP.Promise (resolve, reject) =>
      data =
        grant_type: "password"
        username: credentials.identification
        password: credentials.password

      @makeRequest(data).then (response) =>
        Em.run =>
          expiresAt = @absolutizeExpirationTime(response.expires_in)
          @scheduleAccessTokenRefresh(response.expires_in, expiresAt, response.refresh_token)
          resolve($.extend(response, expires_at: expiresAt))
      , (xhr, status, error) ->
        Em.run ->
          reject(xhr.responseText)

Authentication =
  name: "authentication",
  after: "simple-auth",
  initialize: (container, application) ->
    container.register("authenticator:custom", CustomAuthenticator)

`export default Authentication`

```

**Login Controller** 

```
Login = Em.Controller.extend SimpleAuth.LoginControllerMixin,
  authenticatorFactory: "authenticator:custom"

`export default Login`
```

**Application Route**

```
Application = Em.Route.extend SimpleAuth.ApplicationRouteMixin,
  actions:
    sessionAuthenticationFailed: (error) ->
      @send "alert", "login", "error", "We couldn't find a user with those credentials. Did you make a typo?"

`export default Application`
```

**Authenticated Route**

```
Authenticated = Em.Route.extend SimpleAuth.AuthenticatedRouteMixin,
  beforeModel: (transition) ->
    @_super(transition)

    @controllerFor("application").findAccount().then((account) =>
      account
    ).then null, (reason) ->
      throw reason

  actions:
    error: (reason, transition) ->
      if reason.status is 401
        @send("invalidateSession")
        false
      else
        true

`export default Authenticated`
```
