### ISSUE TITLE
ember-cli with simple-auth: Cannot find module ...

### ISSUE THREAD

**Issue by rustea1** [simplabs/ember-simple-auth#230]
Hi,
for a while now, I'm trying to get ember-cli with simple-auth to work.

Under node_modules I have installed ember-cli-simple-auth.

Question:
Where to put the require('simple-auth/ember'); statement?

What could be the problem for:

> > Errors found in module import statements
> > portal2/controllers/login: Cannot find module "simple-auth/mixins/login-controller-mixin"
> > portal2/routes/application: Cannot find module "simple-auth/mixins/application-route-mixin"
> > portal2/routes/protected: Cannot find module "simple-auth/mixins/authenticated-route-mixin"
> > ENOENT, no such file or directory 'tmp/tree_merger-tmp_dest_dir-Cl9WxEa9.tmp/simple-auth/mixins/login-controller-mixin.js'

I'd really love to move on learning Ember and getting past this issue.
Thanks for a quick hint.

**Comment by mitchiru** [comment]
Same here, latest version. not working with ember-cli 0.1.12.

**Comment by allthesignals** [comment]
Seeing the same issue.

ember-cli version: 1.13.8 

`Error: Could not find module `simple-auth/mixins/application-route-mixin` imported from `ember-auth-sample/routes/application``

I've also installed from the repo as well.

**Comment by marcoow** [comment]
@allthesignals: the module name is now `ember-simple-auth/mixins/application-route-mixin`.

**Comment by devinrhode2** [comment]
@allthesignals See all the simple-auth 1.0 upgrade notes here: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10

**Comment by martinclavell** [comment]
@marcoow have the correct answer, you should probably close this old issue
