### ISSUE TITLE
Event after login OR session restored?

### ISSUE THREAD

**Issue by devinus** [simplabs/ember-simple-auth#813]
Can we add support for an event or an action that gets triggered when the session is restored or on login?

I need to do things like identify the user with other libraries.

**Comment by devinus** [comment]
There doesn't seem to be a method suggested in either https://github.com/simplabs/ember-simple-auth/issues/240 or https://github.com/simplabs/ember-simple-auth/issues/276 that doesn't involve using an observer.

As far as I know, observers are considered a code stink and may even potentially go away at some point.

**Comment by devinus** [comment]
A simple event that's fired on my ApplicationRoute would work wonders.

**Comment by devinus** [comment]
If this wasn't wrapped in `if (trigger)` or there was another event that was always triggered here it would solve my problem (knowing when a user is logged in either when they login or reload the app): https://github.com/simplabs/ember-simple-auth/blob/2464beca521e0ee63c2833e4083cc3e405fbbb26/addon/internal-session.js#L83

**Comment by marcoow** [comment]
The session is restored in 2 cases:

* on application startup in the application route's `beforeModel` method
* whenever the user logs in in another tab or windows of the same application

The latter case is already handled by the [`ApplicationRouteMixin`'s `sessionAuthenticated` method](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionAuthenticated). To handle the former case you just need to check after the promise returned by the application route's `beforeModel` method has resolved (e.g. in the `model` method or by calling `this._super(...arguments).then(() => …)` in the `beforeModel method`) whether the user is authenticated or not. You can just call the same private method in both situations.

**Comment by Kilowhisky** [comment]
I get `this._super.apply(...).then is not a function` when attempting to get the after model. 

Looking at the code i don't see anything relating to the model at all in the application route mixin. 

https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js

**Comment by marcoow** [comment]
See #817 for more info on what I mean. This might eventually be officially supported somehow in the library.

**Comment by Kilowhisky** [comment]
Thanks! 

I know for me i'm trying to use it to resolve a problem where my session account is being recomputed right before logout reload and causing problems with the app that expects the user to be present.

**Comment by marcoow** [comment]
I guess the approach introduced in #817 should work for you then.

**Comment by devinus** [comment]
@marcoow I'm also getting `Error while processing route: user.index this._super.apply(...).then is not a function TypeError: this._super.apply(...).then is not a function`

**Comment by devinus** [comment]
It does, but it get's applied *after* the fact.

https://github.com/simplabs/ember-simple-auth/blob/897779e18be7fbdb3bcf612ae7be188866e6c927/addon/instance-initializers/setup-session-restoration.js#L12

**Comment by devinus** [comment]
I may be doing something bad, but it seems like I *might* just be able to use `afterModel`.

**Comment by devinus** [comment]
Ah, `afterModel` doesn't work for the login version.

**Comment by devinus** [comment]
For posterity, anybody reading up on this that wants to know a method that works this is what I do:

```js
  identifyUser: observer('session.isAuthenticated', function identifyUser() {
    const session = this.get('session');
    if (session.get('isAuthenticated')) {
      const authenticated = session.get('data.authenticated');
      const { id, email } = getProperties(authenticated, 'id', 'email');
      this.get('metrics').identify({ distinctId: id, email });
      this.get('sentry').callRaven('setUserContext', [{ id, email }]);
    }
  }),
```

Obviously, it's still using an observer. :cry:

**Comment by marcoow** [comment]
@devinus you shouldn't use an observer and also don't have to. Check #817 as mentioned above - I guess that approach would work for you as well.

**Comment by devinus** [comment]
I tried that approach, however `sessionAuthenticated` is not called on the reload of my app.

**Comment by marcoow** [comment]
That's why the user is loaded in the application route's `model` hook as well.

**Comment by devinus** [comment]
Is there a way that doesn't require something in the model hook? Maybe I could do a dummy model hook? I do loading of an *actual* user object in someplace entirely different in my app.

**Comment by marcoow** [comment]
You want to do that in the `model` method as that's made for doing exactly that - loading data from the backend. Also that way Ember would display a loading route while the request isn't complete etc.

**Comment by devinus** [comment]
@marcoow I do load the user in a model callback, but you're assuming I load the user in my application route, which isn't the case. I don't need to load my entire user at this point.

**Comment by marcoow** [comment]
You can always move the code from the application route's `model` method to another `model` method in another route.

The point is though that loading the current user on application startup if the session is authenticated on startup would probably work for 90% of the applications and thus is the best thing that ESA can support out of the box. The default way of doing things is never going to be the best way for 100% of the people 100% of the time.

**Comment by devinus** [comment]
> The default way of doing things is never going to be the best way for 100% of the people 100% of the time.

Totally understand, but it *has* been requested quite a lot (https://github.com/simplabs/ember-simple-auth/issues/240, https://github.com/simplabs/ember-simple-auth/issues/276). It also seems trivial to emit a new event whenever `isAuthenticated` becomes true, no where it happens (on restore or or on authentication).

**Comment by marcoow** [comment]
The `sessionAuthenticated` method does exactly what you describe except it doesn't run on application startup. Why exactly is the approach in #817 not working for you?

**Comment by devinus** [comment]
The reason I suggest it is because using this `model` method wont work for that 10% and it's also a really non-obvious solution.

**Comment by marcoow** [comment]
I really don't understand why using the `model` hook doesn't work for you. It is made for loading data from the backend and that's what the approach in #817 does. That also seems a pretty obvious use of the `model` method to me.

**Comment by devinus** [comment]
> Why exactly is the approach in #817 not working for you?

I don't have a `model` callback in my application route, nor do I even need one. My user is not loaded into the application whenever the application starts up. The approach in #817 is requiring the use of a model callback and overriding methods ESA adds to the application route to accomplish the same goal my simple observer does. It makes using an observer seem like the less janky choice.

**Comment by devinus** [comment]
It just seems like a really non-obvious solution to a problem that I imagine is not uncommon.

**Comment by marcoow** [comment]
So you don't have the concept of a current user in your application? If you want to do other sorts of initialization when the app starts up with an authenticated session you can also do that in the `beforeModel` method or so.

**Comment by devinus** [comment]
I have the concept of a current user, but my entire user is not loaded at this point in the application. The information in my ESA session is enough.

Using the `beforeModel` wont work, because of https://github.com/simplabs/ember-simple-auth/issues/813#issuecomment-163805985 and https://github.com/simplabs/ember-simple-auth/issues/813#issuecomment-163806338.

**Comment by marcoow** [comment]
What's the issue with loading the user when the application starts up then? I'd really like to understand that.

**Comment by devinus** [comment]
It's simply not needed. It's an extra request to wait on to load the application and it's a non-trivial amount of data.

**Comment by devinus** [comment]
Also, some areas of the application don't require a user to be logged in at all.

**Comment by marcoow** [comment]
Then you can just load the current user as soon as the user enters the route where you actually need it.

> Also, some areas of the application don't require a user to be logged in at all.

Maybe this is a misunderstanding. You're not resolving the loaded user as the application route's model but only load it in the application route's `model` method **into** the service that makes it available throughout the application so that every part of the app that needs the user can inject that service.

**Comment by devinus** [comment]
> Then you can just load the current user as soon as the user enters the route where you actually need it.

That's exactly what I do. I have an entire `user` route that has the nested routes that require a user under it.

> Maybe this is a misunderstanding. You're not resolving the loaded user as the application route's model but only load it in the application route's model method into the service that makes it available throughout the application so that every part of the app that needs the user can inject that service.

That's a really good idea, however it doesn't solve this problem. I need to do this when my application starts up regardless of if the user is under my route that has already loaded the user or not.

**Comment by marcoow** [comment]
> I need to do this when my application starts up regardless of if the user is under my route that has already loaded the user or not.

And that's exactly what the approach in #817 does.

**Comment by devinus** [comment]
Yes, but it's still loading the user in the application route.

**Comment by marcoow** [comment]
The application route's `model` method is where you load data that you want to be loaded when the application starts up.

**Comment by devinus** [comment]
And I don't want to load the user when the application starts up. I think we're talking in circles at this point.

**Comment by marcoow** [comment]
Yeah, maybe someone else can help clarify this.

**Comment by devinus** [comment]
When my application starts up, I have EVERYTHING I need to know who the user is loaded straight from their session WITHOUT having to load a user from the backend. Pretend my backend is offline.

I need to, as soon as a user loads into the application when they had ALREADY previously logged in, fire off things like identify who the user is with metrics providers, exception trackers, and more.

How do I do that?

**Comment by devinus** [comment]
And I'm proposing that an event could be fired whenever `isAuthenticated` becomes `true`, regardless of how it happened (restore or login).

**Comment by stevenwu** [comment]
Closing this as it's over a year old. We may revisit this when we have more bandwidth, or someone submits a PR.

**Comment by joshsmith** [comment]
Has this been reconsidered? I would also love similar functionality to this, and was surprised to find that `authenticationSucceeded` was not working when the user's `isAuthenticated` becomes `true` on restore.

**Comment by marcoow** [comment]
I still don't think this is necessary - if the session is restored successfully on app startup, it will be authenticated already when the application route's `beforeModel` method runs or if it becomes authenticated while the app already runs the `sessionAuthenticated` will be called. You can apply the same concepts that are explained in the guide on managing a current user to run any other setup code as well:

```js
// app/routes/application.js
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

const { service } = Ember.inject;

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: service(),

  beforeModel() {
    return this._runMySetupCode();
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._runMySetupCode();
  },

  _runMySetupCode() {
    if (this.get('session.isAuthenticated')) {
      // run whatever setup code you need to run…
    }
  }
});
```

@devinus: I'd be interested to hear whether this works for your case as well or if not, why not.

**Comment by joshsmith** [comment]
@marcoow thanks as always for the detailed reply.

So to expand on my use case, I wanted to be able to toggle a connection to a socket (by disconnecting if a socket exists and then connecting) whenever the user loads the app _and_ whenever authentication changes.

What I'm doing now is toggling in:

- the application route's `model` hook (because we assume the user would be authenticated at this point in the lifecycle due to the `ApplicationRouteMixin`)
- `on('authenticationSucceeded')` -  closes an unauthenticated socket and opens an authenticated one
- `on('invalidationSucceeded')` - closes an authenticated socket and opens an unauthenticated one

I believe the `model` hook would be unnecessary if `authenticationSucceeded` fired when the authenticated session was restored. It reads to me as more explicit that connecting a socket is tied to the authentication status.

Please feel free to correct this view!

**Comment by joshsmith** [comment]
Also bear in mind that I'm getting `session.session.authenticated.token` in order to make these socket connections.

**Comment by marcoow** [comment]
Yeah, I think this is a good example for where the above approach works well:

```js
// app/routes/application.js
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

const { service } = Ember.inject;

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: service(),

  beforeModel() {
    if (this.get('session.isAuthenticated')) {
      this._openSocket();
    }
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._openSocket();
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._closeSocket();
  },

  _openSocket() {
    // …
  },

  _closeSocket() {
    // …
  }
});
```

**Comment by joshsmith** [comment]
I’m assuming one of those is supposed to be an invalidated? Otherwise makes sense! Thanks.

**Comment by marcoow** [comment]
ah right - fixed 👍
