### ISSUE TITLE
Error using ember-simple-auth with Ember 2.0.1

### ISSUE THREAD

**Issue by rlb3** [simplabs/ember-simple-auth#662]
Ember : 2.0.1
    Ember Data : 2.0.0
    jQuery : 1.11.3
    Ember Simple Auth : 0.8.0

I'm getting an error after installing ember simple into my ember-cli project.

```Uncaught TypeError: container.lookup is not a function   simple-auth.amd.js:375```

```javascript
      /**
        @method load
        @private
      */
      load: loadConfig(defaults, function(container, config) {
        this.applicationRootUrl = container.lookup('router:main').get('rootURL') || '/';
      })
```

Is there a work around for this?

**Comment by marcoow** [comment]
Ember Simple Auth 0.8.0 doesn't work with Ember 2.0.

**Comment by dknutsen** [comment]
@rlb3 if you haven't found the following yet: until the 1.0 release is final you have to use the jj-abrams branch, lots of good info in [this pr](https://github.com/simplabs/ember-simple-auth/pull/602).

**Comment by rlb3** [comment]
Thanks @dknutsen
